version: 0.1
phases:
  install:
    commands:
      - python -m pip install -q --upgrade -r code/requirements.txt -t code/requirements/
      - cd code/ && zip ../code.zip -qr ./uptime && cd requirements/ && zip ../../code.zip --grow -qr ./* && cd ../../
  build:
    commands:
      - aws cloudformation package --region eu-central-1 --template-file ./backend.yml --s3-bucket uptime-rocks-backend --output-template-file packaged-template.yml
      - aws cloudformation deploy  --region eu-central-1 --template-file ./packaged-template.yml --stack-name uptime-rocks --capabilities CAPABILITY_IAM
